### ISSUE TITLE
Use monograph instead of publication format objects as filter input

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-xmdp-metadata-plugin#1]
Different existing metadata plugin adapters are configured to take one or more different OMP objects as input: DC 1.1 takes publication format objects, NLM 3.0 (among others) submission objects and MODS 3.4. monograph objects. The XMDP plugin started out with publication format objects, since its based on the DC 1.1 code, but I suggest switching to monograph objects instead.

**Comment by withanage** [comment]
Your argument is , that you have better access with monograph objects ? If yes,  go ahead.

**Comment by kadowa** [comment]
No, it's about what we actually want to map/report: a publication format (e.g. pdf, epub or xml) or a monograph (book/edited volume) as a whole regardless of the different formats it's available in.

**Comment by withanage** [comment]
Ok. I see the point.
