### ISSUE TITLE
Handle several files (chapters) and/or publication formats

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-xmdp-metadata-plugin#2]
DNB requests single files or ZIP files, if the publication consists of several files, for transfer. Need to figure out, which files to transfer and where/how to group multiple files, since this is not an OMP feature.

**Comment by withanage** [comment]
> which files to transfer
> As we go for the full monographs, ( futurechapters in back of the head) , we would need to expose the  xml and pdf , in the first phase. As Leo wanted that for internal archiving.
> and where/how to group
> I suggest , that we generate  a  zip file  each time when we upload and update a file in the production status. Where it should be ,  I will  get more info form PKP

**Comment by kadowa** [comment]
Ok, but going this route means the plugin won't be self-contained and it might take some time to obtain a global solution in OMP. It might make sense to think about alternative short-term solutions in the scope of the plugin as well. XMetaDissPlus has an element ddb:fileNumber; I'm wondering if it's not actually possible to report two separate files, if they contain the same content (which is a different case than the chapter question, where several files contain complementary information). Do we have a contact at DNB, who can answer this?

**Comment by withanage** [comment]
I have mailed you inbox.

**Comment by kadowa** [comment]
Maybe @lmaylein can add something?

**Comment by withanage** [comment]
hast Du mit Frau Puls gesprochen ?

**Comment by lmaylein** [comment]
Tatsächlich. In http://d-nb.info/1020009535/34 sieht es so aus, als könnte man mehrere Dateien
mitliefern.

Hier übrigens mal ein Beispiel für XMetaDissPlus bei heiDOK (evtl. nicht XMetaDissPlus2):
http://archiv.ub.uni-heidelberg.de/volltextserver/cgi/oai2?verb=GetRecord&identifier=oai:archiv.ub.uni-heidelberg.de:51&metadataPrefix=XMetaDissPlus

**Comment by lmaylein** [comment]
Nein, Korrektur: In 46 Transfer-URL  steht: "URL, die zur Übermittlung
 von Einzel- und Mehrdateien-Dokumenten bereitgestellt wird. Mehrdateie
n-Dokumente dürfen nur als eine gepackte Datei übermittelt werden
. Die URL, die zur Bildung und Übermittlung erstellt wird, kann für den Transfer temporär 
vorgehalten werden."

**Comment by lmaylein** [comment]
Als Idee: Im Zweifelsfall würde ich die container-Datei on-the-fly generieren, aber nicht beim OAI-Abruf. Via OAI wird eine URL übermittelt, bei deren Aufruf die container-Datei generiert, ausgeliefert und dann wieder gelöscht wird. Dann muss die container-Datei keine "offizielle" OMP-Datei sein sondern es wird nur lesend auf diese zugegriffen.

**Comment by kadowa** [comment]
Stand: Nur full PDF bzw. XML wird übermittelt; Erkennung erfolgt über Genre/Monograph Component, konfigurierbar in den Plugin-Einstellungen (s. https://github.com/kadowa/omp-xmdp-metadata-plugin/commit/cc54f607d0225a3dddcc4639f5af648cd4ed9aba). Das Problem der Container-Generierung wird damit umgangen.
