### ISSUE TITLE
Name schema for persons

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-xmdp-metadata-plugin#3]
Similar to https://github.com/pkp/pkp-lib/blob/master/plugins/metadata/mods34/schema/Mods34NameSchema.inc.php.

**Comment by withanage** [comment]
yes.

**Comment by kadowa** [comment]
This might take more time than initially anticipated, since the XML generation in https://github.com/kadowa/omp-xmdp-oai-plugin/blob/master/OAIMetadataFormat_XMDP.inc.php (derived from the DC OAI plugin) currently does not handle sub-elements. Opened a separate issue for this (https://github.com/kadowa/omp-xmdp-oai-plugin/issues/2).
