### ISSUE TITLE
Use dcterms:hasPart element for chapter association?

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-xmdp-metadata-plugin#4]
Bezeichnung: dcterms:hasPart
Attribut: obligatorisch: xsi:type (dcterms:URI, ddb:ISBN oder ddb:noScheme)
Kardinalität: 0..n
Beschreibung Inhalt: Die beschriebene Hochschulschrift enthält entweder physisch oder logisch die referenzierte Ressource.
XML-Syntax: `<dcterms:hasPart xsi:type=“Identifikation“>Referenzierte Ressource</dcterms:hasPart>`
Beispiel: `<dcterms:hasPart xsi:type=“ddb:noScheme“>Online-Hochschulschrift mit Teil: referenzierter Ressource </dcterms:hasPart>`

(Quelle: http://nbn-resolving.de/urn:nbn:de:101-2012022107)

**Comment by withanage** [comment]
denke sinnvoll

http://dublincore.org/usage/terms/history/#hasPart-003
Wenn ja, 
Bei den Kapiteln sollte   dcterms:isPartOf eingetragen werden, damit einheitlich wird.
Scheint in metadissplus dabei zu sein.
http://d-nb.info/1020009535/34

@lmaylein was meinst Du ?

**Comment by lmaylein** [comment]
Ist es denn in OMP überhaupt möglich, die Kapitel einzeln via OAI bereitzustellen? Wenn das (mal) geht, sollte auf jeden Fall die gegenseitige Verknüpfung eingetragen sein. Sinnvoll ist das auf sicher bei edited volumes. Verlage liefern aber oft auch Metadaten zu Kapiteln aus (das sieht man z.B. wenn man in Summon (HEIDI-Reiter Artikel&Mehr) nach eBooks recherchiert). Was würde man denn dann als Ziel-URL eintragen? Die DOI? 
Die Frage ist noch, wie jemand, der alles via OAI abruft, erkennen kann, dass der eine Record Teil des anderen ist. Das hängt vom jeweiligen Metadatenformat ab. Solange die DOI und/oder die URN bei xMetaDissPluss als Identifier mit ausgeliefert wird, sollte das ja kein Problem sein.

**Comment by kadowa** [comment]
Technisch sehe ich kein Problem, pro Kapitel einen Record zu generieren. Dann wäre allerdings wieder die Frage der Unterscheidung zwischen verschiedenen Formaten offen. Am besten wäre es wahrscheinlich auch hier bei der DNB nachzufragen.
