### ISSUE TITLE
Handle missing language metadata

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-xmdp-metadata-plugin#7]
Press primary locale as fallback?

**Comment by withanage** [comment]
diese würde ich bei anja kopoka  bestätigen lassen ?
@AnjaKonopka  falls  in einenem Monogrpah die Sprache  vergessen wurde ,  können wir es als Presse Sprache annehmen oder einigen ?

**Comment by lmaylein** [comment]
Aus meiner Sicht spricht nichts dagegen, das so zu machen. Ich finde es sinnvoll.

**Comment by ankosi** [comment]
I agree. Press primary locale as fallback in case that language metadata are missing.
