### ISSUE TITLE
Element ddb:rights

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-xmdp-metadata-plugin#8]
Beschreibung in der XMetaDissPlus-Referenz: "Definition der Zugriffsrechte auf die archivierte Dokumentkopie bei der Deutschen Nationalbibliothek. Der Rechteinhaber der Hochschulschrift kann die Deutsche Nationalbibliothek mit dem Recht ausstatten, Nutzern im Internet den unbeschränkten Zugriff auf die Archiv-Version zu gewähren („free“). Beispiel: Wird die Angabe „domain“ ausgewählt, wird der Zugang zur Archiv- Version auf den Zugriff in den Lesesälen der Deutschen Nationalbibliothek eingeschränkt. Wird die Angabe „blocked“ ausgewählt, dann ist der Zugang zur Archiv-Version in den Lesesälen der Deutschen Nationalbibliothek gesperrt. Im Elementinhalt muss das Datum der Freigabe und der Status (domain oder free) nach der Freigabe angegeben werden."

Optionen sind blocked, domain, free, unknown.

Vermutlich standardmäßig "free" für alle Einträge? Oder könnte es hier Einschränkungen geben? Wenn ja, welcher Art?

**Comment by lmaylein** [comment]
Wie ist es denn für heiDOK etc. gelöst? 
Eigentlich wollen wir schon, dass nur unsere Kopie genutzt wird (alleine schon wegen der Statistik). Am liebsten wäre mir, wenn das Archivexemplar in der DNB (im Sinne eines dark archives) gar nicht genutzt würde. Allerdings räumen wir ja vermutlich mit den Lizenzen, unter denen publiziert wird, eh jedem das Recht ein, das beliebig zu kopieren und bereitzustellen.
Ich würde das sicherheitshalber nochmal mit Ef besprechen.

**Comment by kadowa** [comment]
In heiDOK sind alle Einträge, die ich mir angeschaut habe, "free".

**Comment by kadowa** [comment]
Ef stimmt zu, alles auf "free".
